### PR TITLE
[FIX] #28 - Fix test code to not raise NoResultException

### LINKED ISSUE #28: [FIX] Test code raise exception.
**Describe the bug**
`RouletteRecRepositoryTest` and `RouletteRecControllerTest` raise `javax.persistence.NoResultException`.

I see that i have not data on my database. I think test code should be run regardless of data on database.

I suggest create data(used in test) each test.

**To Reproduce**
Run Test without test data. And Failed

**Expected behavior**
Run test successfully.

### PR DESCRIPTION
**Pull request by sgh002400**
- Create data on each test

### CODE REVIEW

File: src/test/java/opgg/weba/JamPick/controller/RouletteRecControllerTest.java [hunk 1]
```diff
@@ -48,6 +49,36 @@
     @Autowired
     RouletteRecRepository rouletteRecRepository;
 
+    @Autowired EntityManager em;
+
+    @BeforeEach
+    public void before() {
+
+        IndieApp indieApp1 = new IndieApp();
```
Comment (gmlwo530) [inline src/test/java/opgg/weba/JamPick/controller/RouletteRecControllerTest.java:57]: `RoutletteRecRepositoryTest.java` file has same code. Make this code to function or class is better to me.

Comment (gmlwo530) [reply src/test/java/opgg/weba/JamPick/controller/RouletteRecControllerTest.java:57]: It's okay that resolve this other task. Resolve this conversation and merge. Good job.

**Review by gmlwo530 — APPROVED** [review]
